apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: smartqueue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: smartqueue
            - name: POSTGRES_USER
              value: sq
            - name: POSTGRES_PASSWORD
              value: sq_pass
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          emptyDir: {}
